# Generated by Django 6.0.1 on 2026-04-22 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del evento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lugar')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('deadline', 'Fecha límite próxima'), ('stalled', 'Sin actividad'), ('budget', 'Presupuesto en riesgo'), ('attendance', 'Asistentes pendientes'), ('milestone', 'Hito importante'), ('suggestion', 'Sugerencia'), ('celebration', 'Celebración')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=200)),
                ('action_label', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('alert_key', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='events.event')),
            ],
            options={
                'verbose_name': 'Alerta de evento',
                'verbose_name_plural': 'Alertas de evento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('business', 'Negocios'), ('academic', 'Académico'), ('creative', 'Creativo'), ('marketing', 'Marketing'), ('social', 'Social')], default='business', max_length=20, verbose_name='Categoría')),
                ('color', models.CharField(default='#3B82F6', help_text='Color representativo en formato hexadecimal (#RRGGBB).', max_length=7, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de evento',
                'verbose_name_plural': 'Plantillas de evento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Plantilla utilizada para crear este evento. Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventtemplate', verbose_name='Plantilla base'),
        ),
        migrations.CreateModel(
            name='TemplateBudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descripción del gasto o ingreso estimado.', max_length=200, verbose_name='Concepto')),
                ('amount_estimate', models.DecimalField(decimal_places=2, default=0, help_text='Valor de referencia. Puede ajustarse al crear el evento.', max_digits=12, verbose_name='Monto estimado')),
                ('item_type', models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso')], default='expense', max_length=10, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('venue', 'Lugar/Espacio'), ('catering', 'Catering'), ('marketing', 'Marketing'), ('technology', 'Tecnología'), ('staff', 'Personal'), ('transport', 'Transporte'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoría')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_budget_items', to='events.eventtemplate')),
            ],
            options={
                'verbose_name': 'Ítem de presupuesto de plantilla',
                'verbose_name_plural': 'Ítems de presupuesto de plantilla',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_title', models.CharField(max_length=150, verbose_name='Checklist')),
                ('item_text', models.CharField(max_length=300, verbose_name='Texto del ítem')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_checklist_items', to='events.eventtemplate')),
            ],
            options={
                'verbose_name': 'Ítem de checklist de plantilla',
                'verbose_name_plural': 'Ítems de checklist de plantilla',
                'ordering': ['checklist_title', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('days_before_event', models.IntegerField(blank=True, help_text='Fecha límite = fecha inicio − N días. Nulo = sin fecha calculada.', null=True, verbose_name='Días antes del evento')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_tasks', to='events.eventtemplate')),
            ],
            options={
                'verbose_name': 'Tarea de plantilla',
                'verbose_name_plural': 'Tareas de plantilla',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EngineMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_key', models.CharField(db_index=True, max_length=150)),
                ('decision_type', models.CharField(max_length=20)),
                ('health_score_at_decision', models.IntegerField(default=0)),
                ('risk_level_at_decision', models.IntegerField(default=0)),
                ('user_acted', models.BooleanField(blank=True, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=50)),
                ('time_to_action_hours', models.FloatField(blank=True, null=True)),
                ('issue_resolved', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_metrics', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_metrics', to='events.event')),
            ],
            options={
                'verbose_name': 'Métrica del engine',
                'verbose_name_plural': 'Métricas del engine',
                'indexes': [models.Index(fields=['user', 'decision_type'], name='events_engi_user_id_367c32_idx'), models.Index(fields=['decision_key'], name='events_engi_decisio_a51ebd_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('tasks', 'Tareas'), ('attendees', 'Asistentes'), ('checklist', 'Checklist'), ('files', 'Archivos'), ('budget', 'Presupuesto')], max_length=20, verbose_name='Módulo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='events.event')),
            ],
            options={
                'verbose_name': 'Módulo de evento',
                'verbose_name_plural': 'Módulos de evento',
                'unique_together': {('event', 'module_type')},
            },
        ),
        migrations.CreateModel(
            name='TemplateModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('tasks', 'Tareas'), ('attendees', 'Asistentes'), ('checklist', 'Checklist'), ('files', 'Archivos'), ('budget', 'Presupuesto')], max_length=20, verbose_name='Módulo')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='events.eventtemplate')),
            ],
            options={
                'verbose_name': 'Módulo de plantilla',
                'verbose_name_plural': 'Módulos de plantilla',
                'unique_together': {('template', 'module_type')},
            },
        ),
    ]
