# Generated by Django 6.0.1 on 2026-05-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Momento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('hora_inicio', models.DateTimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.DateTimeField(blank=True, null=True, verbose_name='Hora de fin')),
                ('tipo', models.CharField(choices=[('protocolo', 'Protocolo'), ('logistica', 'Logística'), ('alimentacion', 'Alimentación'), ('entretenimiento', 'Entretenimiento')], default='protocolo', max_length=20, verbose_name='Tipo')),
                ('importancia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Importancia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentos', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Momento',
                'verbose_name_plural': 'Momentos',
                'ordering': ['hora_inicio'],
            },
        ),
    ]
