# Generated by Django 6.0.1 on 2026-04-22 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_template_budget_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre del evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Organizador'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Plantilla utilizada para crear este evento. Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventtemplate', verbose_name='Plantilla base'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='category',
            field=models.CharField(choices=[('business', 'Negocios'), ('academic', 'Académico'), ('creative', 'Creativo'), ('marketing', 'Marketing'), ('social', 'Social')], default='business', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Color representativo en formato hexadecimal (#RRGGBB).', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='eventtemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='templatechecklistitem',
            name='checklist_title',
            field=models.CharField(max_length=150, verbose_name='Checklist'),
        ),
        migrations.AlterField(
            model_name='templatechecklistitem',
            name='item_text',
            field=models.CharField(max_length=300, verbose_name='Texto del ítem'),
        ),
        migrations.AlterField(
            model_name='templatechecklistitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='templatetask',
            name='days_before_event',
            field=models.IntegerField(blank=True, help_text='Fecha límite = fecha inicio − N días. Nulo = sin fecha calculada.', null=True, verbose_name='Días antes del evento'),
        ),
        migrations.AlterField(
            model_name='templatetask',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='templatetask',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='templatetask',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='templatetask',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
