# Generated by Django 6.0.1 on 2026-05-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_momento_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodule',
            name='module_type',
            field=models.CharField(choices=[('tasks', 'Tareas'), ('attendees', 'Asistentes'), ('checklist', 'Checklist'), ('files', 'Archivos'), ('budget', 'Presupuesto'), ('momentos', 'Momentos')], max_length=20, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='templatemodule',
            name='module_type',
            field=models.CharField(choices=[('tasks', 'Tareas'), ('attendees', 'Asistentes'), ('checklist', 'Checklist'), ('files', 'Archivos'), ('budget', 'Presupuesto'), ('momentos', 'Momentos')], max_length=20, verbose_name='Módulo'),
        ),
    ]
