# Generated by Django 6.0.1 on 2026-04-14 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventalert_templatechecklistitem_templatetask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_key', models.CharField(db_index=True, max_length=150)),
                ('decision_type', models.CharField(max_length=20)),
                ('health_score_at_decision', models.IntegerField(default=0)),
                ('risk_level_at_decision', models.IntegerField(default=0)),
                ('user_acted', models.BooleanField(blank=True, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=50)),
                ('time_to_action_hours', models.FloatField(blank=True, null=True)),
                ('issue_resolved', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_metrics', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métrica del engine',
                'verbose_name_plural': 'Métricas del engine',
                'indexes': [models.Index(fields=['user', 'decision_type'], name='events_engi_user_id_367c32_idx'), models.Index(fields=['decision_key'], name='events_engi_decisio_a51ebd_idx')],
            },
        ),
    ]
