# Generated by Django 6.0.1 on 2026-04-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_description_alter_event_end_date_and_more'),
        ('events', '0004_enginemetrics'),
    ]

    operations = [
    ]
