# Generated by Django 6.0.1 on 2026-06-01 03:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_invitation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invitation_file',
            field=models.FileField(blank=True, help_text='PDF o imagen adjunta al email de invitación.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='invitations/', verbose_name='Archivo de invitación'),
        ),
    ]
