# Generated by Django 6.0.1 on 2026-04-22 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('declined', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado de asistencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.event')),
                ('user', models.ForeignKey(blank=True, help_text='Cuenta BIND del asistente. Dejar vacío para invitados externos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Usuario BIND')),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, help_text='Monto máximo autorizado para el evento.', max_digits=12, verbose_name='Presupuesto total')),
                ('currency', models.CharField(default='COP', help_text='Código ISO 4217 (COP, USD, EUR…).', max_length=3, verbose_name='Moneda')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='events.event')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='events.event')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='modules.checklist')),
            ],
            options={
                'verbose_name': 'Ítem de checklist',
                'verbose_name_plural': 'Ítems de checklist',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='event_files/%Y/%m/', verbose_name='Archivo')),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_type', models.CharField(choices=[('image', 'Imagen'), ('document', 'Documento'), ('spreadsheet', 'Hoja de cálculo'), ('pdf', 'PDF'), ('other', 'Otro')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='events.event')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre descriptivo de la actividad a realizar.', max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('done', 'Completada')], default='pending', max_length=20, verbose_name='Estado')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuario interno responsable de completar esta tarea.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.event')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descripción del gasto o ingreso.', max_length=200, verbose_name='Concepto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('item_type', models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso')], default='expense', max_length=10, verbose_name='Tipo')),
                ('category', models.CharField(choices=[('venue', 'Lugar/Espacio'), ('catering', 'Catering'), ('marketing', 'Marketing'), ('technology', 'Tecnología'), ('staff', 'Personal'), ('transport', 'Transporte'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoría')),
                ('paid', models.BooleanField(default=False, help_text='Marca este ítem como liquidado.', verbose_name='Pagado')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='modules.budget')),
                ('related_task', models.ForeignKey(blank=True, help_text='Tarea del evento a la que corresponde este ítem. Facilita la trazabilidad costo-actividad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='modules.task', verbose_name='Tarea asociada')),
            ],
            options={
                'verbose_name': 'Ítem de presupuesto',
                'verbose_name_plural': 'Ítems de presupuesto',
                'ordering': ['-created_at'],
            },
        ),
    ]
