# Generated by Django 6.0.1 on 2026-04-22 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_file_add_filefield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('declined', 'Rechazado')], default='pending', max_length=20, verbose_name='Estado de asistencia'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Cuenta BIND del asistente. Dejar vacío para invitados externos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Usuario BIND'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.CharField(default='COP', help_text='Código ISO 4217 (COP, USD, EUR…).', max_length=3, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto máximo autorizado para el evento.', max_digits=12, verbose_name='Presupuesto total'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='category',
            field=models.CharField(choices=[('venue', 'Lugar/Espacio'), ('catering', 'Catering'), ('marketing', 'Marketing'), ('technology', 'Tecnología'), ('staff', 'Personal'), ('transport', 'Transporte'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='item_type',
            field=models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso')], default='expense', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='name',
            field=models.CharField(help_text='Descripción del gasto o ingreso.', max_length=200, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='paid',
            field=models.BooleanField(default=False, help_text='Marca este ítem como liquidado.', verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='related_task',
            field=models.ForeignKey(blank=True, help_text='Tarea del evento a la que corresponde este ítem. Facilita la trazabilidad costo-actividad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='modules.task', verbose_name='Tarea asociada'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Usuario interno responsable de completar esta tarea.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('done', 'Completada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Nombre descriptivo de la actividad a realizar.', max_length=200, verbose_name='Título'),
        ),
    ]
