# Generated by Django 6.0.1 on 2026-04-14 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventalert_templatechecklistitem_templatetask'),
        ('modules', '0002_alter_attendee_id_alter_checklist_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='events.event')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_type', models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso')], default='expense', max_length=10)),
                ('category', models.CharField(choices=[('venue', 'Lugar/Espacio'), ('catering', 'Catering'), ('marketing', 'Marketing'), ('technology', 'Tecnología'), ('staff', 'Personal'), ('transport', 'Transporte'), ('other', 'Otro')], default='other', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='modules.budget')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='modules.task')),
            ],
            options={
                'verbose_name': 'Ítem de presupuesto',
                'verbose_name_plural': 'Ítems de presupuesto',
                'ordering': ['-created_at'],
            },
        ),
    ]
