# Generated by Django 6.0.1 on 2026-04-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_attendee_email_alter_attendee_name_and_more'),
        ('modules', '0003_budget_budgetitem'),
    ]

    operations = [
    ]
