# Generated by Django 6.0.1 on 2026-06-01 03:14

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_currency_choices_and_amount_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='event_files/%Y/%m/', verbose_name='Archivo'),
        ),
    ]
