# Generated by Django 4.2.11 on 2026-03-09 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('business', 'Negocios'), ('academic', 'Académico'), ('creative', 'Creativo'), ('marketing', 'Marketing'), ('social', 'Social')], default='business', max_length=20)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de evento',
                'verbose_name_plural': 'Plantillas de evento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventtemplate')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('tasks', 'Tareas'), ('attendees', 'Asistentes'), ('checklist', 'Checklist'), ('files', 'Archivos')], max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='events.eventtemplate')),
            ],
            options={
                'verbose_name': 'Módulo de plantilla',
                'verbose_name_plural': 'Módulos de plantilla',
                'unique_together': {('template', 'module_type')},
            },
        ),
        migrations.CreateModel(
            name='EventModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('tasks', 'Tareas'), ('attendees', 'Asistentes'), ('checklist', 'Checklist'), ('files', 'Archivos')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='events.event')),
            ],
            options={
                'verbose_name': 'Módulo de evento',
                'verbose_name_plural': 'Módulos de evento',
                'unique_together': {('event', 'module_type')},
            },
        ),
    ]
