# Generated by Django 6.0.1 on 2026-04-14 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_id_alter_eventmodule_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('deadline', 'Fecha límite próxima'), ('stalled', 'Sin actividad'), ('budget', 'Presupuesto en riesgo'), ('attendance', 'Asistentes pendientes'), ('milestone', 'Hito importante'), ('suggestion', 'Sugerencia'), ('celebration', 'Celebración')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('critical', 'Crítico')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=200)),
                ('action_label', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('alert_key', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='events.event')),
            ],
            options={
                'verbose_name': 'Alerta de evento',
                'verbose_name_plural': 'Alertas de evento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_title', models.CharField(max_length=150)),
                ('item_text', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_checklist_items', to='events.eventtemplate')),
            ],
            options={
                'verbose_name': 'Ítem de checklist de plantilla',
                'verbose_name_plural': 'Ítems de checklist de plantilla',
                'ordering': ['checklist_title', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10)),
                ('days_before_event', models.IntegerField(blank=True, help_text='Due date = start_date - N días. Null = sin fecha calculada.', null=True)),
                ('order', models.IntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_tasks', to='events.eventtemplate')),
            ],
            options={
                'verbose_name': 'Tarea de plantilla',
                'verbose_name_plural': 'Tareas de plantilla',
                'ordering': ['order'],
            },
        ),
    ]
