# Generated by Django 6.0.1 on 2026-04-29 16:09

import django.core.validators
from django.db import migrations, models


def clean_long_phone_numbers(apps, schema_editor):
    """Nullify phone values that won't fit in the new varchar(16) column.
    Usa __gt en lugar de char_length() para compatibilidad con SQLite y PostgreSQL.
    """
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.filter(phone__isnull=False).exclude(phone='').filter(
        phone__regex=r'.{17,}'   # 17+ caracteres → no cabe en varchar(16)
    ).update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(clean_long_phone_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(
                blank=True,
                max_length=16,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message=(
                            'Ingresa un número válido: entre 7 y 15 dígitos, '
                            'opcionalmente con + al inicio. '
                            'Colombia: +57 seguido de 10 dígitos (ej. +573001234567).'
                        ),
                        regex=r'^\+?\d{7,15}$',
                    )
                ],
            ),
        ),
    ]
