# Generated by Django 6.0.1 on 2026-05-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_fix_fk_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
