# Generated by Django 6.0.1 on 2026-05-27 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_db_socialapp_use_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('invitation', '🎟 Invitación a evento'), ('welcome', '🎉 Bienvenida'), ('digest', '🤖 Resumen semanal (Bynix)'), ('alert', '🚨 Alertas del sistema')], max_length=20)),
                ('custom_subject', models.CharField(blank=True, help_text='Deja vacío para usar el asunto por defecto.', max_length=200)),
                ('custom_body', models.TextField(blank=True, help_text='Mensaje que aparece en el cuerpo del email.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de email',
                'verbose_name_plural': 'Plantillas de email',
                'unique_together': {('user', 'email_type')},
            },
        ),
    ]
